/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import java.awt.Toolkit;

/**
 *
 * @author michaelLaing
 */
public class Menu extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 8981801192523251904L;
	/**
     * Creates new form Menu
     */
    public Menu() {
		setTitle("CAP3104 - Chess");
		setIconImage(Toolkit.getDefaultToolkit().getImage(Menu.class.getResource("/gui/images/TheTab_KGrgb_300ppi.png")));
        initComponents();
        DifficultySelect.setEnabled(false);
        LabelOnePlayer.setVisible(false);
        LabelTwoPlayer.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DifficultySelect = new javax.swing.JComboBox<>();
        StartButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        OnePlayerButton = new javax.swing.JButton();
        TwoPlayerButton = new javax.swing.JButton();
        LabelOnePlayer = new javax.swing.JLabel();
        LabelTwoPlayer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N
        jLabel1.setText("Difficulty");

        jLabel2.setFont(new java.awt.Font("Luminari", 1, 48)); // NOI18N
        jLabel2.setText("LETS PLAY CHESS");

        jLabel3.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N
        jLabel3.setText("Number of Players");

        DifficultySelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard" }));
        DifficultySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DifficultySelectActionPerformed(evt);
            }
        });

        StartButton.setBackground(new java.awt.Color(0, 204, 51));
        StartButton.setForeground(new java.awt.Color(0, 153, 0));
        StartButton.setText("Start!");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        ExitButton.setForeground(new java.awt.Color(255, 51, 51));
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        OnePlayerButton.setText("1 Player");
        OnePlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnePlayerButtonActionPerformed(evt);
            }
        });

        TwoPlayerButton.setText("2 Player");
        TwoPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoPlayerButtonActionPerformed(evt);
            }
        });

        LabelOnePlayer.setText("1 Player Selected - Choose Difficulty");

        LabelTwoPlayer.setText("2 Player Selected ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ExitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StartButton)
                        .addGap(197, 197, 197))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DifficultySelect, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelOnePlayer)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OnePlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TwoPlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(LabelTwoPlayer)))
                .addGap(0, 59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OnePlayerButton)
                    .addComponent(TwoPlayerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DifficultySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelOnePlayer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(LabelTwoPlayer)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartButton)
                    .addComponent(ExitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
System.exit(0);        // TODO add your handling code here:
    }                                          

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	
    }                                           

    private void DifficultySelectActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void OnePlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
    DifficultySelect.setEnabled(true);
    LabelTwoPlayer.setVisible(false);
    LabelOnePlayer.setVisible(true);// TODO add your handling code here:
    }                                               

    private void TwoPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
    LabelTwoPlayer.setVisible(true);
    LabelOnePlayer.setVisible(false);
    DifficultySelect.setEnabled(false);
    }                                               

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> DifficultySelect;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel LabelOnePlayer;
    private javax.swing.JLabel LabelTwoPlayer;
    private javax.swing.JButton OnePlayerButton;
    public javax.swing.JButton StartButton;
    private javax.swing.JButton TwoPlayerButton;
    @SuppressWarnings("unused")
	private javax.swing.ButtonGroup buttonGroup1;
    @SuppressWarnings("unused")
	private javax.swing.ButtonGroup buttonGroup2;
    @SuppressWarnings("unused")
	private javax.swing.ButtonGroup buttonGroup3;
    @SuppressWarnings("unused")
	private javax.swing.ButtonGroup buttonGroup4;
    @SuppressWarnings("unused")
	private javax.swing.ButtonGroup buttonGroup5;
    @SuppressWarnings("unused")
	private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration                   
}